name       : flask-sqlalchemy
version    : 2.3.2
release    : 1
source     :
    - https://github.com/mitsuhiko/flask-sqlalchemy/releases/download/2.3.2/Flask-SQLAlchemy-2.3.2.tar.gz : 5971b9852b5888655f11db634e87725a9031e170f37c0ce7851cf83497f56e53
license    : BSD-3-Clause
component  : programming.python
summary    : Flask-SQLAlchemy is a Flask microframework extension which adds support for the SQLAlchemy SQL toolkit/ORM.
description: |
    Flask-SQLAlchemy is an extension for Flask that adds support for SQLAlchemy to your application. It aims to simplify using SQLAlchemy with Flask by providing useful defaults and extra helpers that make it easier to accomplish common tasks.
rundeps    :
    - flask
    - python-sqlalchemy
build      : |
    %python3_setup
install    : |
    %python3_install
