name       : flask-sqlalchemy
version    : 2.5.1
release    : 8
source     :
    - https://github.com/pallets/flask-sqlalchemy/archive/refs/tags/2.5.1.tar.gz : 53ecdb7bc5947cbea48c49b7b071ab54c64ee78bf9d4afa3c29e5a4755077663
homepage   : https://github.com/pallets/flask-sqlalchemy
license    : BSD-3-Clause
component  : programming.python
summary    : A Flask microframework extension which adds support for the SQLAlchemy SQL toolkit/ORM
description: |
    Flask-SQLAlchemy is an extension for Flask that adds support for SQLAlchemy to your application. It aims to simplify using SQLAlchemy with Flask by providing useful defaults and extra helpers that make it easier to accomplish common tasks.
builddeps  :
    - flask
    - python-mock
    - python-pytest
    - python-sqlalchemy
rundeps    :
    - flask
    - python-sqlalchemy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
